### ISSUE TITLE
eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [walterconticello/proyectofinal-back-grupo1#38]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/walterconticello/proyectofinal-back-grupo1/assets/53904695/0138ec9a-a2a2-487f-9272-f7cf2ddc0572)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by LautaroCruzSrur** [comment]
Resuelto
